# Generated by Django 4.1.4 on 2022-12-23 22:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('photo', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('access_group', models.CharField(choices=[], max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateField(default=datetime.datetime(2022, 12, 23, 22, 0, 13, 924376, tzinfo=datetime.timezone.utc))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('photo', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('access_group', models.CharField(choices=[], max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateField(default=datetime.datetime(2022, 12, 23, 22, 0, 13, 924376, tzinfo=datetime.timezone.utc))),
                ('skills', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
