# Generated by Django 4.1.4 on 2023-10-16 08:45

import apps.users.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('photo', models.TextField(default='...')),
                ('password', models.CharField(max_length=250)),
                ('access_group', models.CharField(choices=[('ADM', 'Administrador'), ('PRO', 'Professor'), ('ALU', 'Aluno')], max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateField(default=datetime.datetime.now)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AttendenceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('enrollments', models.JSONField(default=apps.users.models.AttendenceList.enrollments_default_value)),
                ('details', models.TextField(blank=True, null=True)),
                ('photo', models.TextField(blank=True, null=True)),
                ('total_likes', models.IntegerField(default=0)),
                ('likes', models.JSONField(default=apps.users.models.AttendenceList.users_likes_default_value)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('photo', models.TextField(default='...')),
                ('password', models.CharField(max_length=250)),
                ('access_group', models.CharField(choices=[('ADM', 'Administrador'), ('PRO', 'Professor'), ('ALU', 'Aluno')], max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateField(default=datetime.datetime.now)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('mass', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('workout_tips', models.JSONField(default=dict)),
                ('born_date', models.DateField(blank=True, default=None, null=True)),
                ('last_access', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('photo', models.TextField(default='...')),
                ('password', models.CharField(max_length=250)),
                ('access_group', models.CharField(choices=[('ADM', 'Administrador'), ('PRO', 'Professor'), ('ALU', 'Aluno')], max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateField(default=datetime.datetime.now)),
                ('skills', models.JSONField(default=dict)),
                ('description', models.TextField(blank=True, null=True)),
                ('availability', models.JSONField(default=dict)),
                ('is_hired', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=8)),
                ('created_at', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
