# Generated by Django 4.1.4 on 2023-07-02 19:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('photo', models.TextField(default='...')),
                ('password', models.CharField(max_length=250)),
                ('access_group', models.CharField(choices=[('ADM', 'Administrador'), ('PRO', 'Professor'), ('ALU', 'Aluno')], max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateField(default=datetime.datetime(2023, 7, 2, 19, 35, 45, 587083, tzinfo=datetime.timezone.utc))),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('photo', models.TextField(default='...')),
                ('password', models.CharField(max_length=250)),
                ('access_group', models.CharField(choices=[('ADM', 'Administrador'), ('PRO', 'Professor'), ('ALU', 'Aluno')], max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateField(default=datetime.datetime(2023, 7, 2, 19, 35, 45, 587083, tzinfo=datetime.timezone.utc))),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('mass', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('workout_tips', models.JSONField(default=dict)),
                ('born_date', models.DateField(blank=True, default=None, null=True)),
                ('last_access', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('photo', models.TextField(default='...')),
                ('password', models.CharField(max_length=250)),
                ('access_group', models.CharField(choices=[('ADM', 'Administrador'), ('PRO', 'Professor'), ('ALU', 'Aluno')], max_length=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateField(default=datetime.datetime(2023, 7, 2, 19, 35, 45, 587083, tzinfo=datetime.timezone.utc))),
                ('skills', models.JSONField(default=dict)),
                ('description', models.TextField(blank=True, null=True)),
                ('availability', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=8)),
                ('created_at', models.DateField(default=datetime.datetime(2023, 7, 2, 19, 35, 45, 590718, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='AttendenceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=datetime.datetime(2023, 7, 2, 19, 35, 45, 590107, tzinfo=datetime.timezone.utc))),
                ('status', models.IntegerField(choices=[(0, 'Presente'), (1, 'Falta'), (2, 'Justificado'), (3, 'Reagendado')])),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollment', to='clients.enrollment')),
            ],
        ),
    ]
