# Generated by Django 4.1.4 on 2023-07-02 22:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendencelist',
            name='enrollment',
        ),
        migrations.RemoveField(
            model_name='attendencelist',
            name='status',
        ),
        migrations.AddField(
            model_name='attendencelist',
            name='enrollments',
            field=models.JSONField(default={'enrollments': []}),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 7, 2, 22, 28, 55, 850038, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='attendencelist',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 2, 22, 28, 55, 852853, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 7, 2, 22, 28, 55, 850038, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 7, 2, 22, 28, 55, 850038, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='token',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 7, 2, 22, 28, 55, 853568, tzinfo=datetime.timezone.utc)),
        ),
    ]
