# Generated by Django 4.1.4 on 2023-10-16 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendencelist',
            name='attendence_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendence_class', to='clients.classes'),
        ),
        migrations.AddField(
            model_name='student',
            name='townhouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='townhouse', to='clients.client'),
        ),
    ]
