# Generated by Django 4.1.4 on 2022-12-23 22:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 12, 23, 22, 3, 8, 592595, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='photo',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 12, 23, 22, 3, 8, 592595, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
