# Generated by Django 4.1.4 on 2023-07-02 22:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
        ('users', '0002_remove_attendencelist_enrollment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendencelist',
            name='attendence_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendence_class', to='clients.classes'),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 7, 2, 22, 37, 44, 761173, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='attendencelist',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 2, 22, 37, 44, 764982, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 7, 2, 22, 37, 44, 761173, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 7, 2, 22, 37, 44, 761173, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='token',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 7, 2, 22, 37, 44, 766209, tzinfo=datetime.timezone.utc)),
        ),
    ]
