# Generated by Django 4.1.4 on 2022-12-23 22:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_administrator_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='access_group',
            field=models.CharField(choices=[('ADM', 'Administrador'), ('PRO', 'Professor'), ('ALU', 'Aluno')], max_length=3),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 12, 23, 22, 6, 4, 504745, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='photo',
            field=models.CharField(default='...', max_length=250),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='access_group',
            field=models.CharField(choices=[('ADM', 'Administrador'), ('PRO', 'Professor'), ('ALU', 'Aluno')], max_length=3),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 12, 23, 22, 6, 4, 504745, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.CharField(default='...', max_length=250),
        ),
    ]
