# Generated by Django 4.1.4 on 2022-12-26 22:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_administrator_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 12, 26, 22, 44, 23, 192804, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 12, 26, 22, 44, 23, 192804, tzinfo=datetime.timezone.utc)),
        ),
    ]
