# Generated by Django 4.1.4 on 2023-01-02 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_student_alter_administrator_created_at_and_more'),
        ('users', '0009_alter_administrator_created_at_and_more'),
    ]

    operations = [
    ]
