# Generated by Django 4.1.4 on 2023-09-05 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_attendencelist_photo_alter_administrator_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendencelist',
            name='likes',
            field=models.JSONField(default={'users': []}),
        ),
        migrations.AddField(
            model_name='attendencelist',
            name='total_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 9, 5, 13, 3, 8, 887128, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='attendencelist',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 5, 13, 3, 8, 890370, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 9, 5, 13, 3, 8, 887128, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 9, 5, 13, 3, 8, 887128, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='token',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 9, 5, 13, 3, 8, 891115, tzinfo=datetime.timezone.utc)),
        ),
    ]
