# Generated by Django 4.1.4 on 2023-01-03 21:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_enrollment'),
        ('users', '0013_alter_administrator_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 1, 3, 21, 53, 59, 27048, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='attendencelist',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 1, 3, 21, 53, 59, 29742, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='attendencelist',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollment', to='clients.enrollment'),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 1, 3, 21, 53, 59, 27048, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_access',
            field=models.DateField(default=datetime.datetime(2023, 1, 3, 21, 53, 59, 29081, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 1, 3, 21, 53, 59, 27048, tzinfo=datetime.timezone.utc)),
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
