# Generated by Django 4.1.4 on 2023-03-13 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_administrator_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 3, 13, 17, 51, 3, 887353, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='password',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='attendencelist',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 13, 17, 51, 3, 889862, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 3, 13, 17, 51, 3, 887353, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_access',
            field=models.DateField(default=datetime.datetime(2023, 3, 13, 17, 51, 3, 889215, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 3, 13, 17, 51, 3, 887353, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='password',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='token',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 3, 13, 17, 51, 3, 890370, tzinfo=datetime.timezone.utc)),
        ),
    ]
