# Generated by Django 4.1.4 on 2023-03-13 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_administrator_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 3, 13, 17, 51, 38, 364340, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='password',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='photo',
            field=models.TextField(default='...'),
        ),
        migrations.AlterField(
            model_name='attendencelist',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 3, 13, 17, 51, 38, 367785, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 3, 13, 17, 51, 38, 364340, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_access',
            field=models.DateField(default=datetime.datetime(2023, 3, 13, 17, 51, 38, 366997, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.TextField(default='...'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 3, 13, 17, 51, 38, 364340, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='password',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.TextField(default='...'),
        ),
        migrations.AlterField(
            model_name='token',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2023, 3, 13, 17, 51, 38, 368482, tzinfo=datetime.timezone.utc)),
        ),
    ]
