# Generated by Django 4.1.4 on 2023-10-12 13:13

import apps.users.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_administrator_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='attendencelist',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='attendencelist',
            name='enrollments',
            field=models.JSONField(default=apps.users.models.AttendenceList.enrollments_default_value),
        ),
        migrations.AlterField(
            model_name='attendencelist',
            name='likes',
            field=models.JSONField(default=apps.users.models.AttendenceList.users_likes_default_value),
        ),
        migrations.AlterField(
            model_name='student',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='token',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
