# Generated by Django 4.1.4 on 2023-10-16 08:45

import apps.clients.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.CharField(max_length=5)),
                ('weekday', models.JSONField(blank=True, default=apps.clients.models.Classes.weekday_default_value, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('service', models.CharField(max_length=250)),
                ('duration', models.IntegerField(blank=True, default=1, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('services', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Unsubscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(null=True)),
                ('created', models.DateField(default=datetime.datetime.now, null=True)),
                ('enrollment_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unsubscribe_class', to='clients.classes')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='class_student', to='users.student')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='class_teacher', to='users.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour', models.TimeField()),
                ('status', models.BooleanField(default=False)),
                ('created', models.DateField(default=datetime.datetime.now, null=True)),
                ('professional', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='professional_schedule', to='users.teacher')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_schedule', to='clients.service')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_schedule', to='users.student')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_class', models.JSONField(default=apps.clients.models.Notice.classes_default_value, null=True)),
                ('message', models.TextField(null=True)),
                ('media_url', models.TextField(null=True)),
                ('created', models.DateField(default=datetime.datetime.now, null=True)),
                ('notice_townhouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notice_townhouse', to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('enrollment_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollment_class', to='clients.classes')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student', to='users.student')),
            ],
        ),
        migrations.AddField(
            model_name='classes',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client', to='clients.client'),
        ),
        migrations.AddField(
            model_name='classes',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teacher', to='users.teacher'),
        ),
    ]
