# Generated by Django 4.1.4 on 2023-10-17 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='media_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
