# Generated by Django 4.1.4 on 2023-08-09 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='weekday',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
