# Generated by Django 4.1.4 on 2022-12-26 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
