# Generated by Django 4.1.4 on 2023-01-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_classes_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
