# Generated by Django 4.1.4 on 2023-09-29 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_administrator_created_at_and_more'),
        ('clients', '0004_alter_classes_weekday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour', models.TimeField()),
                ('status', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='professional_schedule', to='users.teacher')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_schedule', to='clients.service')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_schedule', to='users.student')),
            ],
        ),
    ]
