# Generated by Django 4.1.4 on 2023-01-03 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_administrator_created_at_and_more'),
        ('clients', '0005_client_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('enrollment_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollment_class', to='clients.classes')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student', to='users.student')),
            ],
        ),
    ]
