# Generated by Django 4.1.4 on 2023-01-03 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_enrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='price',
        ),
        migrations.AddField(
            model_name='classes',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
