# Generated by Django 4.1.4 on 2023-04-18 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_remove_client_price_classes_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='duration',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
