# Generated by Django 4.1.4 on 2023-10-08 00:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_remove_schedule_updated_alter_schedule_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 8, 0, 17, 33, 480592, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
