# Generated by Django 4.1.4 on 2023-10-09 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_alter_schedule_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 9, 11, 40, 57, 432010, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
