# Generated by Django 4.1.4 on 2023-10-09 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0009_alter_schedule_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 9, 11, 44, 47, 546658, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
