# Generated by Django 4.1.4 on 2023-10-10 17:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_administrator_created_at_and_more'),
        ('clients', '0010_alter_schedule_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client', to='clients.client'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='classes',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teacher', to='users.teacher'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='enrollment_class', to='clients.classes'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student', to='users.student'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 10, 17, 14, 9, 465801, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_schedule', to='clients.service'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='student_schedule', to='users.student'),
        ),
    ]
