# Generated by Django 4.1.4 on 2023-10-12 13:13

import apps.clients.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_administrator_created_at_and_more'),
        ('clients', '0012_alter_schedule_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='weekday',
            field=models.JSONField(blank=True, default=apps.clients.models.Classes.weekday_default_value, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='services',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='created',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
        migrations.CreateModel(
            name='Unsubscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(null=True)),
                ('enrollment_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='unsubscribe_class', to='clients.classes')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='class_teacher', to='users.teacher')),
            ],
        ),
    ]
