# Generated by Django 4.1.4 on 2023-10-12 13:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0013_alter_classes_weekday_alter_client_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unsubscribe',
            name='created',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
