# Generated by Django 4.1.4 on 2023-10-12 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_administrator_created_at_and_more'),
        ('clients', '0014_unsubscribe_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='unsubscribe',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='class_student', to='users.student'),
        ),
    ]
