# Generated by Django 4.1.4 on 2023-10-15 21:39

import apps.clients.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0015_unsubscribe_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='created',
            field=models.DateField(default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='unsubscribe',
            name='created',
            field=models.DateField(default=datetime.datetime.now, null=True),
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_class', models.JSONField(default=apps.clients.models.Notice.classes_default_value, null=True)),
                ('message', models.TextField(null=True)),
                ('media_url', models.TextField(null=True)),
                ('created', models.DateField(default=datetime.datetime.now, null=True)),
                ('notice_townhouse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notice_townhouse', to='clients.client')),
            ],
        ),
    ]
